import { generateMasterSeed, deriveHkdfKey } from '../utils/signature/keyUtils.js';
import { signMessage } from '../utils/signature/signMessage.js';
import { hashMessage } from '../utils/signature/hashMessage.js';
import { logError } from '../setting/logger.js';

/**
 * Signs a message with two keys: the main key and an HKDF-derived key.
 *
 * Both keys are derived from masterSeed using HKDF, but with different info strings.
 *
 * @param {Object} message - The message object to be signed.
 * @param {string} mnemonic - The mnemonic phrase used to generate the master seed.
 * @param {string} alphanumericPart - The alphanumeric string used as info for HKDF derivation.
 * @returns {{
 *   originalMessage: Object,
 *   hash: string,
 *   signatures: Array<{
 *     type: string,
 *     r: string,
 *     s: string,
 *     pub: string,
 *     der: string,
 *     signatureCompact: string
 *   }>
 * }} - Returns the original message, its hash, and the signatures generated by both keys.
 */
export function signWithBothKeys(message, mnemonic, alphanumericPart) {
  try {
    console.log('Generating master seed from mnemonic...');
    const seed = generateMasterSeed(mnemonic);
    console.log('Master seed generated:', seed.toString('hex'));

    console.log('Hashing message...');
    const hash = hashMessage(message);
    console.log('Message hash:', hash);

    // Define different info for main and hkdf keys so that the keys are different
    const mainKeyInfo = Buffer.from(`mainKey-${alphanumericPart}`);
    const hkdfKeyInfo = Buffer.from(`hkdfKey-${alphanumericPart}`);

    // Derive main private key через HKDF
    const mainPrivateKey = deriveHkdfKey(seed, mainKeyInfo);
    console.log('Main private key (HKDF derived):', mainPrivateKey.toString('hex'));

    // Derive HKDF private key через HKDF з іншим info
    const hkdfPrivateKey = deriveHkdfKey(seed, hkdfKeyInfo);
    console.log('HKDF-derived private key:', hkdfPrivateKey.toString('hex'));

    console.log('Signing message with main private key...');
    const mainSignature = signMessage(mainPrivateKey, message);
    console.log('Main signature:', mainSignature);

    console.log('Signing message with HKDF private key...');
    const hkdfSignature = signMessage(hkdfPrivateKey, message);
    console.log('HKDF signature:', hkdfSignature);

    return {
      originalMessage: message,
      hash,
      signatures: [
        { type: 'main', ...mainSignature },
        { type: 'hkdf', ...hkdfSignature },
      ],
    };
  } catch (error) {
    logError(error, 'signWithBothKeys');
    throw error;
  }
}
